In [48]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
#print(arr.size)
#print(arr.shape)
print(arr.ndim)


2


In [49]:
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])
print("Original array:", arr)
print("Original shape:", arr.shape)

# Reshape to a 2D array (2 rows, 3 columns)
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)
print("New shape:", reshaped_arr.shape)

Original array: [1 2 3 4 5 6]
Original shape: (6,)
[[1 2 3]
 [4 5 6]]
New shape: (2, 3)


In [3]:
def pythonsum(n):
   a = range(n)
   b = range(n)
   c = []
   for i in range(n):
       a[i] = i ** 2
       b[i] = i ** 3
       c.append(a[i] + b[i])
   return c

In [5]:
def pythonsum(n):
    a = [0] * n
    b = [0] * n
    c = []
    for i in range(n):
        a[i] = i ** 2
        b[i] = i ** 3
        c.append(a[i] + b[i])
    return c


In [9]:
import numpy as np
def numpysum(n):
  a = np.arange(n) ** 2  #Creates an array [0,1,..n-1] and element-wise sqauring
  b = np.arange(n) ** 3
  c = a + b #element wise adding - NO LOOP Overhead, hence Memory Efficient
  return c

In [ ]:
numpysum(3)

array([ 0,  2, 12])

In [11]:
#Creating Arrays from Sequences
#a list of numbers will create a 1D array,
#a list of lists will create a 2D array,
#further nested lists will create higher-dimensional arrays. 
#In general, any array object is called an ndarray in NumPy.

In [12]:
import numpy as np
a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [51]:
import numpy as np
np.array([127, 128, 129], dtype=np.int32) 

array([127, 128, 129], dtype=int32)

| Name       | Alias(es)       | Size   | Range                           |
| ---------- | --------------- | ------ | ------------------------------- |
| `np.int8`  | `int8`          | 8-bit  | −128 to 127                     |
| `np.int16` | `int16`         | 16-bit | −32,768 to 32,767               |
| `np.int32` | `int32`, `int_` | 32-bit | −2,147,483,648 to 2,147,483,647 |
| `np.int64` | `int64`         | 64-bit | −9.2e18 to 9.2e18 (approx.)     |


In [16]:
import numpy as np
np.array([127, 128, 129], dtype=np.int8)
# You will get an error, why?

In [54]:
#ARRAY CREATION FUNCTIONS
import numpy as np
#np.arange(10) #0 TO BEFORE 10, Step Value 1
#np.arange(2, 10, dtype=float) #?
np.arange(2, 3, 0.1) #?

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [20]:
#best practice for numpy.arange is to use integer start, end, and step values.

In [55]:
np.linspace(1., 4., 6)


array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [ ]:
#numpy.linspace will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values. 
#For example:

# np.linspace(start, stop, num)

# Start: 1.0

# Stop: 4.0

# num: 6 (number of samples including both endpoints)

# The interval is divided into 5 equal steps (because 6 points mean 5 intervals).

In [57]:
#2D Array Creation
#The 2D array creation functions e.g. numpy.eye, numpy.diag, and numpy.vander define 
#properties of special matrices represented as 2D arrays.
import numpy as np
#np.eye(3)
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [60]:
np.eye(3, 5, k=-2) #optional k argument, what happens when k>0, k<0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [30]:
# numpy.diag can define either a square 2D array with given values along the diagonal or if given a 2D array 
# returns a 1D array that is only the diagonal elements. 
# The two array creation functions can be helpful while doing linear algebra, as such:

In [32]:
import numpy as np
#np.diag([1, 2, 3])
np.diag([1, 2, 3], 1)
#a = np.array([[1, 2], [3, 4]])
#np.diag(a)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [33]:
# np.diag(v, k=1):

# When v is a 1D array, np.diag creates a 2D square matrix with v placed along the k-th diagonal.

# k=1 → the diagonal above the main (first superdiagonal).

# To hold this upper diagonal, NumPy creates a (n + k) × (n + k) square matrix, where n is the length of the input array.

# So for [1, 2, 3]: Length = 3, k = 1, Matrix shape = 4 × 4

# # Diagonal values are placed at positions: (0,1), (1,2), (2,3)

In [ ]:
#Vandermonde Matrix
import numpy as np
#np.vander(np.linspace(0, 2, 5), 2)
#np.vander([1, 2, 3, 4], 2)
#np.vander((1, 2, 3, 4), 4)

| x | x¹ | x⁰ |
| - | -- | -- |
| 1 | 1  | 1  |
| 2 | 2  | 1  |
| 3 | 3  | 1  |
| 4 | 4  | 1  |


| x | x³ | x² | x¹ | x⁰ |
| - | -- | -- | -- | -- |
| 1 | 1  | 1  | 1  | 1  |
| 2 | 8  | 4  | 2  | 1  |
| 3 | 27 | 9  | 3  | 1  |
| 4 | 64 | 16 | 4  | 1  |


In [ ]:
#np.vander(x, N) creates a Vandermonde matrix from a 1D input array x.

# [[x₁**(N-1), x₁**(N-2), ..., x₁**0],
#  [x₂**(N-1), x₂**(N-2), ..., x₂**0],
#  ...
#  [xₙ**(N-1), xₙ**(N-2), ..., xₙ**0]]

# So each row is a decreasing power of an element from x.


In [38]:
np.vander(np.linspace(0, 2, 5), 2)
#np.linspace(0, 2, 5) → [0. , 0.5, 1. , 1.5, 2. ]
# N = 2 → two columns: x**1, x**0

np.vander([1, 2, 3, 4], 2)
#Input: [1, 2, 3, 4]
# No of Columns 2
#N = 4 → columns: x**3, x**2, x**1, x**0

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1]])

In [39]:
#Each row is [x**3, x**2, x, 1] for each x in the input.

| Code                                 | Shape    | Meaning                                           |
| ------------------------------------ | -------- | ------------------------------------------------- |
| `np.vander(np.linspace(0, 2, 5), 2)` | `(5, 2)` | 2-column Vandermonde matrix of `[0, 0.5, ..., 2]` |
| `np.vander([1, 2, 3, 4], 2)`         | `(4, 2)` | Powers: `[x, 1]` for each x                       |
| `np.vander((1, 2, 3, 4), 4)`         | `(4, 4)` | Powers: `[x**3, x**2, x, 1]`                      |
